import { Tender, Subcontractor, SubcontractorBid, BOQItem, RiskItem } from "./types/tender";

export const mockSubcontractors: Subcontractor[] = [
  {
    id: "sub-1",
    name: "Milano Scavi & Demolizioni S.r.l.",
    specialty: "excavation",
    rating: 4.8,
    riskScore: "Basso",
    completedProjects: 42,
    durcValid: true,
    soaCategory: "OS21 Classifica III",
  },
  {
    id: "sub-2",
    name: "ItalCementi Strutture S.p.A.",
    specialty: "concrete",
    rating: 4.9,
    riskScore: "Basso",
    completedProjects: 85,
    durcValid: true,
    soaCategory: "OG1 Classifica V",
  },
  {
    id: "sub-3",
    name: "Edilizia Generale Lombarda S.r.l.",
    specialty: "concrete",
    rating: 4.2,
    riskScore: "Medio",
    completedProjects: 19,
    durcValid: true,
    soaCategory: "OG1 Classifica III",
  },
  {
    id: "sub-4",
    name: "Milano Impianti & Cablaggi S.r.l.",
    specialty: "installations",
    rating: 4.6,
    riskScore: "Basso",
    completedProjects: 31,
    durcValid: true,
    soaCategory: "OG11 Classifica IV",
  },
  {
    id: "sub-5",
    name: "Nuova Clima S.r.l. Termoidraulica",
    specialty: "installations",
    rating: 3.9,
    riskScore: "Alto",
    completedProjects: 14,
    durcValid: false, // DURC EXPIRED!
    soaCategory: "OG11 Classifica II",
  },
  {
    id: "sub-6",
    name: "Brescia Finiture & Decorazioni S.a.s.",
    specialty: "finishing",
    rating: 4.5,
    riskScore: "Basso",
    completedProjects: 22,
    durcValid: true,
    soaCategory: "OS6 Classifica II",
  },
];

export const mockSubBids: SubcontractorBid[] = [
  {
    id: "bid-1",
    subcontractorId: "sub-1",
    subcontractorName: "Milano Scavi & Demolizioni S.r.l.",
    workPackageId: "pkg-1",
    priceProposed: 98000,
    deliveryDays: 20,
    notes: "Include noleggio macchinari speciali per centri storici.",
    isSubmitted: true,
  },
  {
    id: "bid-2",
    subcontractorId: "sub-2",
    subcontractorName: "ItalCementi Strutture S.p.A.",
    workPackageId: "pkg-2",
    priceProposed: 410000,
    deliveryDays: 45,
    notes: "Prezzo comprensivo di casseri autoportanti e additivi antigelo.",
    isSubmitted: true,
  },
  {
    id: "bid-3",
    subcontractorId: "sub-3",
    subcontractorName: "Edilizia Generale Lombarda S.r.l.",
    workPackageId: "pkg-2",
    priceProposed: 385000,
    deliveryDays: 50,
    notes: "Sconto cassa 2% per stati avanzamento lavori (SAL) brevi.",
    isSubmitted: true,
  },
  {
    id: "bid-4",
    subcontractorId: "sub-4",
    subcontractorName: "Milano Impianti & Cablaggi S.r.l.",
    workPackageId: "pkg-3",
    priceProposed: 280000,
    deliveryDays: 30,
    notes: "Compresi cablaggi in fibra e collaudi finali.",
    isSubmitted: true,
  },
  {
    id: "bid-5",
    subcontractorId: "sub-5",
    subcontractorName: "Nuova Clima S.r.l. Termoidraulica",
    workPackageId: "pkg-3",
    priceProposed: 245000,
    deliveryDays: 35,
    notes: "Sconto volume applicato. Richiede anticipo 15%.",
    isSubmitted: true,
  },
  {
    id: "bid-6",
    subcontractorId: "sub-6",
    subcontractorName: "Brescia Finiture & Decorazioni S.a.s.",
    workPackageId: "pkg-4",
    priceProposed: 68000,
    deliveryDays: 15,
    notes: "Tinteggiature ecologiche ad acqua classe A+.",
    isSubmitted: true,
  },
];

export const initialTenders: Tender[] = [
  {
    id: "tender-1",
    title: "Ristrutturazione Scuola Elementare - Milano",
    cig: "CIG: 9482715F31",
    stazioneAppaltante: "Comune di Milano - Direzione Edilizia Scolastica",
    deadlineISO: "2026-06-25",
    budgetEUR: 1250000,
    status: "bidding",
    region: "Lombardia",
    createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    boq: [
      { id: "item-1", category: "excavation", description: "Scavo a sezione obbligata in materie di qualsiasi natura per fondazioni e condutture, eseguito a macchina compreso il carico su autocarro ed il trasporto alle discariche.", quantity: 1850, unit: "mc", unitPriceEUR: 22.50 },
      { id: "item-2", category: "concrete", description: "Calcestruzzo strutturale classe C25/30 per fondazioni, travi di collegamento e muri contro terra, gettato in opera con pompa, inerti con diametro max 25mm.", quantity: 640, unit: "mc", unitPriceEUR: 118.00 },
      { id: "item-3", category: "steel", description: "Acciaio in barre tonde ad aderenza migliorata tipo B450C tagliato, sagomato e posto in opera per armature di cemento armato di qualsiasi diametro.", quantity: 45000, unit: "kg", unitPriceEUR: 1.85 },
      { id: "item-4", category: "concrete", description: "Muratura portante in blocchi termolaterizi spessore 30cm, posti in opera con malta bastarda cementizia, compresi ponteggi interni e spigolature.", quantity: 1200, unit: "mq", unitPriceEUR: 62.00 },
      { id: "item-5", category: "installations", description: "Fornitura e posa di impianto elettrico centralizzato comprendente quadri di piano, canalizzazioni corrugate esterne ed interne, cablaggi e frutti certificati Vimar.", quantity: 1, unit: "cad", unitPriceEUR: 165000.00 },
      { id: "item-6", category: "installations", description: "Impianto termoidraulico e di climatizzazione centralizzato con pompa di calore aria-acqua, fan coil di piano, tubazioni isolate in rame e valvole termostatiche.", quantity: 1, unit: "cad", unitPriceEUR: 185000.00 },
      { id: "item-7", category: "finishing", description: "Intonaco civile interno tirato in piano con stabilitura fine di calce idrata, applicato a mano o a macchina su pareti verticali e soffitti.", quantity: 4800, unit: "mq", unitPriceEUR: 14.80 },
      { id: "item-8", category: "finishing", description: "Pavimentazione in gres porcellanato antiscivolo R10 per aule e corridoi scolastici, posato con collante cementizio, sigillatura dei giunti.", quantity: 2100, unit: "mq", unitPriceEUR: 42.50 },
    ],
    workPackages: [
      { id: "pkg-1", name: "Opere di Scavo e Movimento Terra", category: "excavation", estimatedBudget: 110000 },
      { id: "pkg-2", name: "Opere Strutturali e Cemento Armato", category: "concrete", estimatedBudget: 480000 },
      { id: "pkg-3", name: "Impianti Tecnologici (MEP)", category: "installations", estimatedBudget: 350000 },
      { id: "pkg-4", name: "Opere di Finitura e Pavimentazione", category: "finishing", estimatedBudget: 190000 },
    ],
    computed: {
      totalCostEUR: 686775,
      suggestedBidEUR: 755452.5,
      marginPercent: 10,
      riskScore: 35,
      winProbability: 72,
    },
    riskItems: [
      {
        id: "risk-1",
        code: "DURC_EXPIRED",
        level: "high",
        message: "Il subappaltatore 'Nuova Clima S.r.l.' inserito per la parte Impianti presenta un DURC scaduto in data 15/05/2026.",
        impactScore: 15,
        status: "Flagged",
        resolutionHint: "Richiedere il DURC aggiornato o selezionare un subappaltatore alternativo conforme (es. Milano Impianti).",
      },
      {
        id: "risk-2",
        code: "SOA_REQUIRED",
        level: "medium",
        message: "L'importo delle opere strutturali (480.000€) richiede la qualificazione SOA Categoria OG1 - Classifica II o superiore.",
        impactScore: 10,
        status: "Resolved",
        resolutionHint: "La tua azienda possiede la qualifica OG1 Classifica III. Requisito pienamente soddisfatto.",
      },
      {
        id: "risk-3",
        code: "DELIVERY_DELAY",
        level: "medium",
        message: "Il capitolato d'appalto prevede una penale dell'1‰ al giorno sull'importo contrattuale per ritardi oltre i 120 giorni naturali consecutivi.",
        impactScore: 10,
        status: "Flagged",
        resolutionHint: "Includere un buffer del 15% sulla pianificazione delle finiture interne per compensare possibili ritardi negli approvvigionamenti.",
      },
      {
        id: "risk-4",
        code: "SAFETY_COSTS_NON_REDUCIBLE",
        level: "low",
        message: "Gli oneri per la sicurezza e la salute nei cantieri pari a 34.200€ non sono soggetti a ribasso d'asta.",
        impactScore: 5,
        status: "Resolved",
        resolutionHint: "Verificato: gli oneri della sicurezza sono stati scorporati correttamente dall'offerta economica.",
      },
    ],
    subcontractorBids: [],
  },
  {
    id: "tender-2",
    title: "Realizzazione Parco Urbano e Piste Ciclabili - Torino",
    cig: "CIG: 8593817A55",
    stazioneAppaltante: "Città Metropolitana di Torino",
    deadlineISO: "2026-07-12",
    budgetEUR: 680000,
    status: "draft",
    region: "Piemonte",
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    boq: [
      { id: "item-201", category: "excavation", description: "Scavo per fondazione cassonetto stradale ed aree a verde, compreso allontanamento ed indennità di conferimento.", quantity: 3400, unit: "mc", unitPriceEUR: 18.20 },
      { id: "item-202", category: "concrete", description: "Cordoli in pietra di Luserna per delimitazione aiuole e piste ciclabili, posati su rinfianco di calcestruzzo.", quantity: 1600, unit: "m", unitPriceEUR: 38.00 },
      { id: "item-203", category: "finishing", description: "Pavimentazione drenante ecologica in misto granulare legata con resine poliuretaniche per percorsi pedonali.", quantity: 4500, unit: "mq", unitPriceEUR: 45.00 },
    ],
    workPackages: [
      { id: "pkg-201", name: "Scavi e preparazione terreno", category: "excavation", estimatedBudget: 75000 },
      { id: "pkg-202", name: "Opere edili e cordolature", category: "concrete", estimatedBudget: 120000 },
      { id: "pkg-203", name: "Forniture arboree e arredo urbano", category: "finishing", estimatedBudget: 220000 },
    ],
    computed: {
      totalCostEUR: 325180,
      suggestedBidEUR: 357698,
      marginPercent: 10,
      riskScore: 25,
      winProbability: 55,
    },
    riskItems: [
      {
        id: "risk-201",
        code: "ENVIRONMENTAL_CONSTRAINT",
        level: "high",
        message: "L'area d'intervento ricade all'interno di una zona a vincolo fluviale. Richiesta autorizzazione paesaggistica preventiva.",
        impactScore: 25,
        status: "Flagged",
        resolutionHint: "Verificare che la Stazione Appaltante abbia già depositato l'autorizzazione paesaggistica negli allegati di gara.",
      },
    ],
    subcontractorBids: [],
  },
  {
    id: "tender-3",
    title: "Restauro Conservativo Colosseo - Roma",
    cig: "CIG: 7394851A02",
    stazioneAppaltante: "Ministero della Cultura - Soprintendenza Archeologica",
    deadlineISO: "2026-08-05",
    budgetEUR: 4250000,
    status: "draft",
    region: "Lazio",
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    boq: [
      { id: "item-301", category: "steel", description: "Allestimento ponteggio metallico tubolare sospeso ad alta sicurezza su facciata curva Colosseo", quantity: 12000, unit: "mq", unitPriceEUR: 68.00 },
      { id: "item-302", category: "finishing", description: "Pulizia chimica di superfici in travertino mediante microsabbiatura controllata e impacchi assorbenti", quantity: 18500, unit: "mq", unitPriceEUR: 45.50 },
      { id: "item-303", category: "concrete", description: "Consolidamento micro-fratture su elementi lapidei mediante iniezione di resine acriliche stabili", quantity: 4500, unit: "cad", unitPriceEUR: 120.00 },
      { id: "item-304", category: "installations", description: "Impianto di illuminazione monumentale LED RGBW a basso impatto visivo con cablaggio schermato e fibra", quantity: 1, unit: "cad", unitPriceEUR: 380000.00 },
    ],
    workPackages: [
      { id: "pkg-301", name: "Opere di ponteggio e sicurezza ad alta quota", category: "steel", estimatedBudget: 850000 },
      { id: "pkg-302", name: "Opere di restauro specialistico superfici lapidee", category: "finishing", estimatedBudget: 1250000 },
      { id: "pkg-303", name: "Impianto elettrico e illuminotecnico artistico", category: "installations", estimatedBudget: 420000 },
    ],
    computed: {
      totalCostEUR: 2577750,
      suggestedBidEUR: 2835525,
      marginPercent: 10,
      riskScore: 45,
      winProbability: 62,
    },
    riskItems: [
      {
        id: "risk-301",
        code: "UNESCO_CONSTRAINT",
        level: "high",
        message: "Lavori su bene protetto UNESCO. Richiede nulla osta Soprintendenza Archeologica entro 15 giorni dall'apertura del cantiere.",
        impactScore: 25,
        status: "Flagged",
        resolutionHint: "Verificare che il nulla osta sia depositato nella sezione B1 del portale di gara.",
      },
      {
        id: "risk-302",
        code: "SPECIALIST_SOA_OS2A",
        level: "high",
        message: "L'importo delle opere di restauro (1.25M) richiede qualifica SOA Categoria OS2-A Classifica III.",
        impactScore: 20,
        status: "Resolved",
        resolutionHint: "La tua impresa detiene qualifica OS2-A Classifica IV. Requisito pienamente soddisfatto.",
      },
    ],
    subcontractorBids: [],
  },
  {
    id: "tender-4",
    title: "Nuovo Presidio Ospedaliero - Napoli",
    cig: "CIG: 8274910F11",
    stazioneAppaltante: "ASL Napoli 1 Centro - Ufficio Tecnico",
    deadlineISO: "2026-09-18",
    budgetEUR: 8750000,
    status: "analyzing",
    region: "Campania",
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    boq: [
      { id: "item-401", category: "excavation", description: "Scavo a sezione obbligata per le fondazioni della nuova ala ospedaliera in aree limitrofe a reparti attivi", quantity: 15400, unit: "mc", unitPriceEUR: 24.00 },
      { id: "item-402", category: "concrete", description: "Fornitura e getto di calcestruzzo autocompattante SCC C30/37 per fondazioni e pilastri antisismici", quantity: 4800, unit: "mc", unitPriceEUR: 132.00 },
      { id: "item-403", category: "installations", description: "Impianto di ventilazione meccanica controllata a pressione positiva con filtri assoluti HEPA H14 per sale operatorie", quantity: 1, unit: "cad", unitPriceEUR: 1250000.00 },
      { id: "item-404", category: "finishing", description: "Pareti divisorie fonoassorbenti in cartongesso accoppiato a lastre di piombo per schermatura raggi X", quantity: 3800, unit: "mq", unitPriceEUR: 88.00 },
    ],
    workPackages: [
      { id: "pkg-401", name: "Scavi e preparazione fondazioni antisismiche", category: "excavation", estimatedBudget: 420000 },
      { id: "pkg-402", name: "Strutture in cemento armato antisismico C30/37", category: "concrete", estimatedBudget: 1850000 },
      { id: "pkg-403", name: "Impianti speciali di ventilazione clinica ed HEPA", category: "installations", estimatedBudget: 1600000 },
      { id: "pkg-404", name: "Finiture radioprotette e schermate per sale operatorie", category: "finishing", estimatedBudget: 750000 },
    ],
    computed: {
      totalCostEUR: 2587600,
      suggestedBidEUR: 2846360,
      marginPercent: 10,
      riskScore: 35,
      winProbability: 40,
    },
    riskItems: [
      {
        id: "risk-401",
        code: "VIBRATION_MONITORING",
        level: "high",
        message: "Lavori limitrofi a reparti attivi (terapia intensiva). Previsto obbligo di monitoraggio vibrazionale continuo in fase di cantiere.",
        impactScore: 20,
        status: "Flagged",
        resolutionHint: "Installare sismografi a soglia collegati al sistema di telecontrollo della direzione sanitaria.",
      },
      {
        id: "risk-402",
        code: "SOA_OG11_REQUIRED",
        level: "medium",
        message: "La parte MEP ospedaliera richiede qualificazione SOA OG11 Classifica VI o associazione temporanea d'impresa.",
        impactScore: 15,
        status: "Flagged",
        resolutionHint: "Strutturare una RTI (Raggruppamento Temporaneo) con subappaltatore specializzato in impianti OG11.",
      },
    ],
    subcontractorBids: [],
  },
  {
    id: "tender-5",
    title: "Consolidamento Fondazioni Canal Grande - Venezia",
    cig: "CIG: 6519283B44",
    stazioneAppaltante: "Provveditorato Interregionale Opere Pubbliche Veneto",
    deadlineISO: "2026-06-15",
    budgetEUR: 2100000,
    status: "won",
    region: "Veneto",
    createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    boq: [
      { id: "item-501", category: "concrete", description: "Palificazione in legno di larice di diametro 22cm e lunghezza 6m conficcata nel fondale melmoso", quantity: 1200, unit: "cad", unitPriceEUR: 185.00 },
      { id: "item-502", category: "concrete", description: "Iniezioni consolidanti cementizie bentonitiche fluide a bassa pressione sotto i muri di fondazione storici", quantity: 380, unit: "mc", unitPriceEUR: 260.00 },
      { id: "item-503", category: "excavation", description: "Fornitura e posa di pontoni galleggianti motorizzati per stoccaggio macchinari e materiali in laguna", quantity: 1, unit: "cad", unitPriceEUR: 180000.00 },
      { id: "item-504", category: "finishing", description: "Ricostruzione paramento murario sommerso in mattoni cotti a mano veneziani e malta idraulica naturale", quantity: 850, unit: "mq", unitPriceEUR: 195.00 },
    ],
    workPackages: [
      { id: "pkg-501", name: "Lavorazioni lagunari e pontoni di servizio", category: "excavation", estimatedBudget: 280000 },
      { id: "pkg-502", name: "Consolidamento profondo e palificate storiche", category: "concrete", estimatedBudget: 820000 },
      { id: "pkg-503", name: "Restauro paramenti murari in ambiente salino", category: "finishing", estimatedBudget: 450000 },
    ],
    computed: {
      totalCostEUR: 666550,
      suggestedBidEUR: 733205,
      marginPercent: 10,
      riskScore: 10,
      winProbability: 88,
    },
    riskItems: [
      {
        id: "risk-501",
        code: "WATER_TRAFFIC_LIMITS",
        level: "medium",
        message: "Attività soggetta a regolazione dei canali navigabili di Venezia. Richiesto piano di coordinamento traffico acqueo.",
        impactScore: 10,
        status: "Resolved",
        resolutionHint: "Piano di coordinamento approvato dall'Ufficio Traffico Acqueo di Venezia.",
      },
    ],
    subcontractorBids: [],
  },
];
